Disable some parts of os_perf_bsd.cpp. the 'struct frame' variable included with sys/user.h clash with 'class frame' from src/hotspot/share/runtime/frame.hpp
In file included from src/hotspot/os/bsd/os_perf_bsd.cpp:37:
In file included from /usr/include/sys/user.h:38:
In file included from /usr/include/machine/pcb.h:41:
/usr/include/machine/frame.h:131:8: error: redefinition of 'frame'
struct frame {
       ^
/usr/ports/java/openjdk11/work/openjdk-jdk11u-jdk-11.0.4-11-2/src/hotspot/share/runtime/frame.hpp:55:7: note: previous definition is here
class frame {